name: CI Automation Tests

on:
  push:
    branches:
      - master  # Change if needed
  pull_request:
    branches:
      - master  # Change if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'zulu' or 'temurin' for OpenJDK
          java-version: '11'

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y xvfb libxi6 libgconf-2-4

      - name: Set Up Chrome and Chromedriver
        run: |
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          sudo apt install -y chromium-chromedriver

      - name: Set Up Edge and Edgedriver (Optional)
        run: |
          sudo apt install -y microsoft-edge-stable
          EDGE_VERSION=$(microsoft-edge --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          sudo apt install -y microsoft-edgedriver

      - name: Start Xvfb
        run: Xvfb :99 -ac &

      - name: Run Tests with Xvfb
        run: DISPLAY=:99 mvn test
