name: CI Automation Pipeline

on:
  push:
    branches:
      - master  # Change to 'main' if needed
  pull_request:
    branches:
      - master

jobs:
  automation-tests:
    runs-on: ubuntu-latest  # Use an Ubuntu Linux runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Start xvfb
        run: Xvfb :99 -ac &

      - name: Run Tests with xvfb
        run: DISPLAY=:99 mvn clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4  # Fixed version
        with:
          name: test-reports
          path: target/surefire-reports
